default:
    listen:
        host:   127.0.0.1
        port:   7890

    gridfs:
        host:               localhost
        port:               27017
        auto_reconnect:     true
        database:           pixlish_gridfs

    debug: false
    # php uses, by default, BinaryData type 2, which node does not support
    # the workaround is ot strip first 4 bytes from stream if bytes 3-4 are 0x0002
    php_fix: true